# Generated by Django 4.0.1 on 2022-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls_app', '0003_alter_book_category_alter_book_retal_price_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, default='photos/def/3.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, default='photos/def/3.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
