# Generated by Django 4.0.1 on 2022-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls_app', '0004_alter_book_photo_author_alter_book_photo_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, default='def/2.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, default='def/1.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
