# Generated by Django 4.0.1 on 2022-02-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls_app', '0008_delete_login_book_totol_renatl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='totol_renatl',
            new_name='totol_renatll',
        ),
    ]
